insert into brand (name, description, created_at, updated_at) values ('Sports Windbreaker', 'Lightweight windbreaker for outdoor activities.', '2025-05-18', '2025-01-03');
insert into brand (name, description, created_at, updated_at) values ('Portable Charger with Solar Panel', 'Eco-friendly charger with a built-in solar panel for outdoor use.', '2025-02-12', '2024-10-02');
insert into brand (name, description, created_at, updated_at) values ('Organic Coconut Oil', 'Cold-pressed coconut oil, perfect for cooking, baking, or skin care.', '2025-02-04', '2024-09-18');
insert into brand (name, description, created_at, updated_at) values ('Chicken Fajita Kit', 'All ingredients included for delicious chicken fajitas.', '2024-09-09', '2025-01-08');
insert into brand (name, description, created_at, updated_at) values ('Frozen Cauliflower Rice', 'Convenient and low-carb alternative to traditional rice.', '2024-10-13', '2024-09-14');
insert into brand (name, description, created_at, updated_at) values ('Pet Travel Carrier', 'Comfortable carrier for small pets during travel.', '2025-05-15', '2025-04-12');
insert into brand (name, description, created_at, updated_at) values ('Phone Screen Protector', 'Tempered glass screen protector for smartphones.', '2025-04-22', '2025-04-25');
insert into brand (name, description, created_at, updated_at) values ('Herb Drying Rack', 'Mesh drying rack for preserving herbs and flowers.', '2025-04-10', '2025-07-17');
insert into brand (name, description, created_at, updated_at) values ('Field Journal', 'Durable journal for nature observations and notes.', '2025-01-22', '2025-04-05');
insert into brand (name, description, created_at, updated_at) values ('Honey Garlic Sauce', 'A delicious sauce perfect for stir-frying or glazing meats.', '2025-04-13', '2025-08-03');
insert into brand (name, description, created_at, updated_at) values ('Multi-Function Smartphone Holder', 'Versatile holder that can be used on desks, cars, and more.', '2025-03-31', '2025-07-14');
insert into brand (name, description, created_at, updated_at) values ('DIY Candle Making Kit', 'Everything you need to make your own candles.', '2025-04-30', '2025-06-22');
insert into brand (name, description, created_at, updated_at) values ('Almond Quinoa Salad', 'Healthy salad made with quinoa, almonds, and mixed greens, perfect for a light meal.', '2024-10-24', '2025-05-03');
insert into brand (name, description, created_at, updated_at) values ('Vegetarian Chili', 'Hearty chili made with beans and vegetables, a savory meal option.', '2024-08-13', '2025-01-30');
insert into brand (name, description, created_at, updated_at) values ('Pet Activity Tracker', 'GPS collar that monitors your pet''s location and activity level.', '2024-10-11', '2024-08-12');
insert into brand (name, description, created_at, updated_at) values ('Peanut Butter Banana Smoothie Mix', 'Smoothie mix combining peanut butter and banana, great for a quick breakfast.', '2024-12-18', '2025-01-20');
insert into brand (name, description, created_at, updated_at) values ('Basil-infused Olive Oil', 'Extra virgin olive oil infused with fresh basil.', '2024-10-01', '2025-05-27');
insert into brand (name, description, created_at, updated_at) values ('Vegetarian Chili', 'Hearty chili made with beans and vegetables, a savory meal option.', '2025-03-06', '2024-08-22');
insert into brand (name, description, created_at, updated_at) values ('Vegan Cheese', 'Dairy-free cheese alternative for your favorite dishes.', '2025-06-10', '2024-12-28');
insert into brand (name, description, created_at, updated_at) values ('Leather Wallet', 'Genuine leather wallet with multiple compartments.', '2025-04-22', '2025-05-14');
